#!/usr/bin/env bash

# Installs phpMyAdmin plus a lightweight PHP built-in server (no Apache).
# Works on Debian/Ubuntu/WSL; prompts for sudo only when needed.

set -euo pipefail

log() {
    printf '[check-install] %s\n' "$1"
}

require_command() {
    if ! command -v "$1" >/dev/null 2>&1; then
        log "ERROR: required command '$1' not found in PATH."
        exit 1
    fi
}

if [[ "$(uname -s)" != "Linux" ]]; then
    log "ERROR: This script is intended for Debian/Ubuntu/WSL environments."
    exit 1
fi

require_command sudo
require_command apt-get
require_command debconf-set-selections

SUDO="sudo"
if [[ "$(id -u)" -eq 0 ]]; then
    SUDO=""
fi

PACKAGES=(php-cli phpmyadmin php-mbstring php-zip php-gd php-json php-curl)

if ! dpkg -s phpmyadmin >/dev/null 2>&1; then
    log "Pre-seeding phpMyAdmin installation options (no bundled web server, no dbconfig)."
    printf 'phpmyadmin phpmyadmin/reconfigure-webserver multiselect\n' | $SUDO debconf-set-selections
    printf 'phpmyadmin phpmyadmin/dbconfig-install boolean false\n' | $SUDO debconf-set-selections
fi

log "Updating apt package index."
$SUDO apt-get update

log "Installing required packages: ${PACKAGES[*]}"
DEBIAN_FRONTEND=noninteractive $SUDO apt-get install -y "${PACKAGES[@]}"

log "Enabling PHP mbstring extension."
$SUDO phpenmod mbstring

SNIPPET="/etc/phpmyadmin/conf.d/localhost.inc.php"
log "Writing phpMyAdmin host locking snippet to $SNIPPET"
$SUDO tee "$SNIPPET" >/dev/null <<'EOF'
<?php
/* Auto-generated by nonprofit_finance_db/check-install.sh */
$cfg['Servers'][1]['host'] = '127.0.0.1';
$cfg['Servers'][1]['port'] = '3306';
$cfg['Servers'][1]['AllowNoPassword'] = false;
$cfg['Servers'][1]['auth_type'] = 'cookie';
EOF

PMA_PORT="${PMA_PORT:-8081}"
SERVICE_FILE="/etc/systemd/system/phpmyadmin-light.service"
PHP_BIN="/usr/bin/env php"
PHP_CMD="$PHP_BIN -S 127.0.0.1:${PMA_PORT} -t /usr/share/phpmyadmin"

SYSTEMD_AVAILABLE=1
if ! $SUDO systemctl list-units >/dev/null 2>&1; then
    SYSTEMD_AVAILABLE=0
fi

if [[ $SYSTEMD_AVAILABLE -eq 1 ]]; then
    log "Configuring systemd service for lightweight phpMyAdmin server on port ${PMA_PORT}."
    $SUDO tee "$SERVICE_FILE" >/dev/null <<EOF
[Unit]
Description=phpMyAdmin lightweight PHP server
After=network.target mysql.service mariadb.service

[Service]
Type=simple
WorkingDirectory=/usr/share/phpmyadmin
ExecStart=$PHP_CMD
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

    log "Reloading systemd and enabling phpmyadmin-light service."
    $SUDO systemctl daemon-reload
    $SUDO systemctl enable --now phpmyadmin-light.service
else
    log "Systemd not detected; launching phpMyAdmin via background PHP server."
    RUNTIME_DIR="${HOME}/.local/share/phpmyadmin-light"
    PID_FILE="${RUNTIME_DIR}/phpmyadmin-light.pid"
    LOG_FILE="${RUNTIME_DIR}/phpmyadmin-light.log"
    mkdir -p "$RUNTIME_DIR"

    if [[ -f "$PID_FILE" ]]; then
        if kill -0 "$(cat "$PID_FILE")" >/dev/null 2>&1; then
            log "Existing phpMyAdmin process detected (PID $(cat "$PID_FILE")); stopping it."
            kill "$(cat "$PID_FILE")" || true
            sleep 1
        fi
    fi

    log "Starting phpMyAdmin: $PHP_CMD"
    (cd /usr/share/phpmyadmin && nohup $PHP_CMD >>"$LOG_FILE" 2>&1 & echo $! >"$PID_FILE")
    log "Non-systemd mode logs: $LOG_FILE (PID file: $PID_FILE). Restart by rerunning this script."
fi

WSL_IP="$(hostname -I | awk '{print $1}')"
log "phpMyAdmin lightweight server listening on http://127.0.0.1:${PMA_PORT} (WSL IP http://$WSL_IP:${PMA_PORT})."
log "Log in with the NON_PROFIT_USER / NON_PROFIT_PASSWORD credentials from your .env file."
